version: '3.7'

services:
  nxtcldbackup:
    container_name: nxtcld-backup
    build:
      context: .
      dockerfile: alpine.dockerfile
    init: true
    environment:
      - UNISONLOCALHOSTNAME=nxtcld-backup
      - SOURCE=/mnt/source
      - BACKUP=/mnt/backup
    volumes:
      - unison-conf:/root/.unison
      - /mnt/nextcloud:/mnt/source
      - /mnt/raid1/nextcloud:/mnt/backup

volumes:
  unison-conf: