services:
  nxtcldbackup:
    container_name: nxtcldbackup
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    environment:
      - UNISONLOCALHOSTNAME=nxtcldbackup
      - SOURCE=/mnt/source
      - BACKUP=/mnt/backup
      - RETENTION_DAYS=90
    volumes:
      - unison-conf:/root/.unison
      - /mnt/nextcloud:/mnt/source
      - /mnt/nas:/mnt/backup

volumes:
  unison-conf:
