#!/bin/ash

TIMESTAMP="date +\"%b %e %T %Z\""

mkdir -p /mnt/backup/weekly
#rsync -r --delete /mnt/backup/daily/ /mnt/backup/weekly/

echo "`eval $TIMESTAMP` Starting unison weekly backup..." >> /var/log/backup
unison nextcloud_weekly >> /var/log/backup
echo -e "\n`eval $TIMESTAMP`  ... unison weekly backup finished" >> /var/log/backup
